'use client';

export interface User {
  // Unique identifier for the user.
  userId: string;
  // Username of the user.
  username: string;
  organization: {
    // Unique identifier for the organization.
    organizationId: string;
    // Name of the organization.
    organizationName: string;
  };
  session:
    | {
        // read-only session .
        read?: ReadOnlySession;
        // read-write session details.
        write?: ReadWriteSession;
        // Authenticated client associated with the session.
        authClient: any;
      }
    | undefined;
}

export interface ReadOnlySession {
  // Read-only session token for `X-Session` header
  token: string;
  // Expiry time in seconds since Unix epoch.
  expiry: number;
}

export interface ReadWriteSession {
  // Credential bundle for iFrame client, generated by `createReadWriteSession` or `createApiKeys`.
  credentialBundle: string;
  // Expiry time in seconds since Unix epoch.
  expiry: number;
}

export default function Pro() {
  return null;
  // const [user, setUser] = useState<User | null>(null);
  //
  // const getUser = async () => {
  //   if (turnkey) {
  //     const user = await turnkey.getCurrentUser();
  //     setUser(user!);
  //   }
  // };
  //
  // useEffect(() => {
  //   if (turnkey) getUser();
  // }, [turnkey]);
  //
  // const getSignWith = async () => {
  //   // This will return the authIframeClient with the credential bundle injected
  //   const client = await getActiveClient();
  //
  //   // The user's sub-organization id
  //   const organizationId = user?.organization.organizationId;
  //
  //   // Get the user's wallets
  //   const wallets = await client?.getWallets({
  //     organizationId,
  //   });
  //
  //   // Get the first wallet of the user
  //   const walletId = wallets?.wallets[0].walletId ?? "";
  //
  //   // Use the `walletId` to get the accounts associated with the wallet
  //   const accounts = await client?.getWalletAccounts({
  //     organizationId,
  //     walletId,
  //   });
  //
  //   // These accounts use the same path, but just different address formats.
  //   // ADDRESS_FORMAT_UNCOMPRESSED is the critical format as it's required for both
  //   // signing and to derive other Cosmos-SDK-based addresses.
  //   const accounts2 = [
  //     {
  //       curve: "CURVE_SECP256K1" as const,
  //       pathFormat: "PATH_FORMAT_BIP32" as const,
  //       path: "m/44'/118'/0'/0/0" as const,
  //       addressFormat: "ADDRESS_FORMAT_UNCOMPRESSED" as const,
  //     },
  //     {
  //       curve: "CURVE_SECP256K1" as const,
  //       pathFormat: "PATH_FORMAT_BIP32" as const,
  //       path: "m/44'/118'/0'/0/0" as const,
  //       addressFormat: "ADDRESS_FORMAT_COSMOS" as const,
  //     },
  //   ];
  //
  //   const wallet = await client?.createWallet({
  //     organizationId: organizationId,
  //     walletName: "Ashwin4",
  //     accounts: accounts2,
  //   });
  //
  //   const signWith = wallet?.addresses[0];
  //
  //   // const privateKeys = await client?.getPrivateKeys();
  //   //
  //
  //   // const signWith = accounts?.accounts[0].address ?? "";
  //   console.log({ client, accounts, signWith, wallets, user, walletId });
  //
  //   const odxWallet = await TurnkeyDirectWallet.init({
  //     config: {
  //       organizationId:
  //         "0a70ae47-6700-4bde-9245-84f1be64ea79" ?? organizationId!,
  //       signWith:
  //         "04c1e428ed736cf21f2022997c11cefc89ffc44442d8f70520c5e6bb30c93e683b782ebb7fcd2a85f7270d96168b7ceb71a505e6cbef46cd928aad385df5d5c838" ??
  //         signWith!,
  //       // "02dbb9d26fce3382d3589da2d141c372b4877e2c14f71aa6f804a5da125a8cb097",
  //       client: client!,
  //     },
  //     prefix: "odx",
  //   });
  //
  //   const acc = await odxWallet.getAccounts();
  //   console.log("ACC", { acc, odxWallet });
  //
  //   const signingClient = await SigningStargateClient.connectWithSigner(
  //     GRPC_ADDR,
  //     // @ts-expect-error hello
  //     odxWallet,
  //     { registry },
  //   );
  //
  //   const balances = await signingClient.getAllBalances(acc[0].address ?? "");
  //
  //   console.log("BALANCES", balances);
  //
  //   return signWith;
  // };
  //
  // return (
  //   <div className="p-4">
  //     <Button onClick={getSignWith}>Get sign with</Button>
  //   </div>
  // );
}
