import styles from './index.module.css';
import { memo, useEffect, useRef } from 'react';
import {
  ChartingLibraryWidgetOptions,
  LanguageCode,
  ResolutionString,
  widget,
} from '../../public/static/charting_library';
import { useTheme } from 'next-themes';

export const TVChartContainer = memo((props: Partial<ChartingLibraryWidgetOptions>) => {
  const chartContainerRef = useRef<HTMLDivElement>() as React.MutableRefObject<HTMLInputElement>;
  const { theme, systemTheme } = useTheme();

  const currentTheme = theme === 'system' ? systemTheme : theme;

  useEffect(() => {
    const widgetOptions: ChartingLibraryWidgetOptions = {
      symbol: props.symbol,
      // BEWARE: no trailing slash is expected in feed URL
      datafeed: new (window as any).Datafeeds.UDFCompatibleDatafeed(
        // 'https://demo_feed.tradingview.com',
        'https://pf.od.exchange',
        undefined,
        {
          maxResponseLength: 1000,
          expectedOrder: 'latestFirst',
        }
      ),
      interval: props.interval as ResolutionString,
      container: chartContainerRef.current,
      library_path: props.library_path,
      locale: props.locale as LanguageCode,
      disabled_features: [
        'use_localstorage_for_settings',
        'header_symbol_search',
        'header_saveload',
        'header_chart_type',
        'header_compare',
        'header_undo_redo',
        'header_screenshot',
        'header_symbol_search',
        'go_to_date',
        'symbol_info',
        'symbol_search_hot_key',
        'border_around_the_chart',
        'header_settings',
        'save_shortcut',
        'chart_template_storage',
      ],
      enabled_features: [],
      charts_storage_url: props.charts_storage_url,
      charts_storage_api_version: props.charts_storage_api_version,
      client_id: props.client_id,
      user_id: props.user_id,
      fullscreen: props.fullscreen,
      autosize: props.autosize,
      theme: currentTheme === 'dark' ? 'dark' : 'light',
      custom_themes: {
        light: {
          // Color that overrides blue (based on --primary: 221 83% 53%)
          color1: [
            '#e6f0ff',
            '#cce0ff',
            '#b3d1ff',
            '#99c2ff',
            '#80b3ff',
            '#66a4ff',
            '#4d95ff',
            '#3386ff',
            '#1a77ff',
            '#0068ff',
            '#0052cc',
            '#0047b3',
            '#003d99',
            '#003380',
            '#002966',
            '#001f4d',
            '#001433',
            '#000a1a',
            '#000000',
            '#000000',
          ],
          // Color that overrides grey (based on --secondary: 210 40% 96.1%)
          color2: [
            '#f5f7fa',
            '#e6eaf0',
            '#d7dde6',
            '#c8d0dc',
            '#b9c3d2',
            '#aab6c8',
            '#9ba9be',
            '#8c9cb4',
            '#7d8faa',
            '#6e82a0',
            '#5f7596',
            '#50688c',
            '#415b82',
            '#324e78',
            '#23416e',
            '#143464',
            '#0a1b2f',
            '#0a1b2f',
            '#0a1b2f',
            '#0a1b2f',
          ],
          // Color that overrides red (based on --destructive: 0 72% 51%)
          color3: [
            '#fff0f0',
            '#ffe1e1',
            '#ffd3d3',
            '#ffc4c4',
            '#ffb5b5',
            '#ffa6a6',
            '#ff9797',
            '#ff8888',
            '#ff7a7a',
            '#ff6b6b',
            '#ff4d4d',
            '#ea4747',
            '#d54040',
            '#bf3a3a',
            '#aa3333',
            '#952d2d',
            '#802727',
            '#6a2020',
            '#551a1a',
            '#401313',
          ],
          // Color that overrides green (based on --success: 142 76% 36%)
          color4: [
            '#f2fdf8',
            '#e5faf0',
            '#d7f8e9',
            '#caf5e1',
            '#bdf3da',
            '#b0f1d2',
            '#a2eecb',
            '#95ecc3',
            '#88e9bc',
            '#7be7b4',
            '#60e2a5',
            '#58cf97',
            '#50bc8a',
            '#48aa7c',
            '#40976e',
            '#388460',
            '#307153',
            '#285e45',
            '#204b37',
            '#183929',
          ],
          // Color that overrides orange (based on --warning: 38 95% 64%)
          color5: [
            '#fff5e6',
            '#ffebcc',
            '#ffe1b3',
            '#ffd799',
            '#ffcd80',
            '#ffc366',
            '#ffb94d',
            '#ffaf33',
            '#ffa51a',
            '#ff9b00',
            '#cc7c00',
            '#b36d00',
            '#995e00',
            '#804f00',
            '#664000',
            '#4d3100',
            '#332200',
            '#1a1100',
            '#000000',
            '#000000',
          ],
          // Color that overrides purple (based on --accent: 319 84% 67%)
          color6: [
            '#fef0f7',
            '#fde0ef',
            '#fcd0e7',
            '#fbc0df',
            '#fab0d7',
            '#f9a0cf',
            '#f890c7',
            '#f780bf',
            '#f670b7',
            '#f560af',
            '#f450a7',
            '#c34086',
            '#a3306e',
            '#832056',
            '#63103e',
            '#430026',
            '#33001d',
            '#230014',
            '#13000b',
            '#000000',
          ],
          // Color that overrides yellow (based on --chart-4: 43 74% 66%)
          color7: [
            '#fff9e6',
            '#fff3cc',
            '#ffedb3',
            '#ffe799',
            '#ffe180',
            '#ffdb66',
            '#ffd54d',
            '#ffcf33',
            '#ffc91a',
            '#ffc300',
            '#cc9c00',
            '#b38a00',
            '#997800',
            '#806600',
            '#665400',
            '#4d4200',
            '#332b00',
            '#1a1500',
            '#000000',
            '#000000',
          ],
          white: '#ffffff',
          black: '#000000',
        },
        dark: {
          color1: [
            '#fbefea',
            '#f7dfd5',
            '#f3cfc0',
            '#efbfaa',
            '#ebaf95',
            '#e89f80',
            '#e48f6b',
            '#e07f56',
            '#dc6f41',
            '#d85f2b',
            '#d03f01',
            '#bf3a01',
            '#ad3501',
            '#9c2f01',
            '#8b2a01',
            '#792501',
            '#682001',
            '#0a0057',
            '#050045',
            '#0c012c',
          ],
          color2: [
            '#f1f1f1',
            '#d0d0d0',
            '#c2c2c2',
            '#9d9292',
            '#8b8b83',
            '#888888',
            '#676767',
            '#4e4e4e',
            '#2a2a2a',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
            '#1c1e22',
          ],
          color3: [
            '#fff0f0',
            '#ffe1e1',
            '#ffd3d3',
            '#ffc4c4',
            '#ffb5b5',
            '#ffa6a6',
            '#ff9797',
            '#ff8888',
            '#ff7a7a',
            '#ff6b6b',
            '#ff4d4d',
            '#ea4747',
            '#d54040',
            '#bf3a3a',
            '#aa3333',
            '#952d2d',
            '#802727',
            '#6a2020',
            '#551a1a',
            '#401313',
          ],
          color4: [
            '#f2fffb',
            '#e6fff7',
            '#d9fff2',
            '#ccffee',
            '#bfffea',
            '#b3ffe6',
            '#a6ffe1',
            '#99ffdd',
            '#8cffd9',
            '#80ffd5',
            '#66ffcc',
            '#5eeabb',
            '#55d5aa',
            '#4dbf99',
            '#44aa88',
            '#3c9577',
            '#338066',
            '#2b6a55',
            '#225544',
            '#1a4033',
          ],
          color5: [
            '#fffff0',
            '#ffffe0',
            '#feffd1',
            '#feffc2',
            '#feffb2',
            '#feffa3',
            '#fdff94',
            '#fdff84',
            '#fdff75',
            '#fdff66',
            '#fcff47',
            '#e7ea41',
            '#d2d53b',
            '#bdbf35',
            '#a8aa2f',
            '#939529',
            '#7e8024',
            '#696a1e',
            '#545518',
            '#3f4012',
          ],
          color6: [
            '#fff1ff',
            '#ffe2ff',
            '#ffd4ff',
            '#ffc5ff',
            '#ffb7ff',
            '#ffa9ff',
            '#ff9aff',
            '#ff8cff',
            '#ff7dff',
            '#ff6fff',
            '#ff52ff',
            '#ea4bea',
            '#d544d5',
            '#bf3ebf',
            '#aa37aa',
            '#953095',
            '#802980',
            '#6a226a',
            '#551b55',
            '#401540',
          ],
          color7: [
            '#eff8ff',
            '#dff1ff',
            '#cfeaff',
            '#bee3ff',
            '#aedcff',
            '#9ed5ff',
            '#8eceff',
            '#7ec7ff',
            '#6ec0ff',
            '#5db9ff',
            '#3dabff',
            '#389dea',
            '#338fd5',
            '#2e80bf',
            '#2972aa',
            '#246495',
            '#1f5680',
            '#19476a',
            '#143955',
            '#0f2b40',
          ],
          white: '#f0f0f0',
          black: '#000000',
        },
      } as any,
    };

    const tvWidget = new widget(widgetOptions);

    tvWidget.onChartReady(() => {});

    return () => {
      tvWidget.remove();
    };
  }, [props, theme]);

  return (
    <>
      {/* <header className={styles.VersionHeader}>
        <h1>TradingView Charting Library and Next.js Integration Example</h1>
      </header> */}
      <div ref={chartContainerRef} className={styles.TVChartContainer} style={{ height: '100%' }} />
    </>
  );
});

TVChartContainer.displayName = 'TVChartContainer';
